apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: rabbit1
  name: rabbit1
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: containers.cisco.com/jaganaga/rabbitnode
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
