apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --provider openshift convert
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbit3
  name: rabbit3
spec:
  ports:
  - name: "1885"
    port: 1885
    targetPort: 1883
  - name: "5674"
    port: 5674
    targetPort: 5672
  - name: "8885"
    port: 8885
    targetPort: 8883
  - name: "15674"
    port: 15674
    targetPort: 15672
  selector:
    io.kompose.service: rabbit3
status:
  loadBalancer: {}
