apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: rabbit2
  name: rabbit2
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: jaganaga/rabbitnode
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
