apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --provider openshift convert
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbit1
  name: rabbit1
spec:
  ports:
  - name: "1883"
    port: 1883
    targetPort: 1883
  - name: "5672"
    port: 5672
    targetPort: 5672
  - name: "8883"
    port: 8883
    targetPort: 8883
  - name: "15672"
    port: 15672
    targetPort: 15672
  selector:
    io.kompose.service: rabbit1
status:
  loadBalancer: {}
