apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose --provider openshift convert
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbit1
  name: rabbit1
spec:
  replicas: 1
  selector:
    io.kompose.service: rabbit1
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: rabbit1
    spec:
      containers:
      - image: 'containers.cisco.com/jaganaga/rabbitnode'
        name: rabbit1
        securityContext:
          runAsUser: 999
        ports:
        - containerPort: 1883
        - containerPort: 5672
        - containerPort: 8883
        - containerPort: 15672
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - rabbit1
      from:
        kind: ImageStreamTag
        name: rabbit1:latest
    type: ImageChange
status: {}
